import { ChevronDown, ChevronRight, FlaskConical, Layers3, ShieldCheck, Wrench } from "lucide-react";
import { useState } from "react";
import type { AlliedStandard, Language, StandardResult } from "../types";
import { allGroups, groupDescription, matrixGroupCode, matrixHeading, matrixSubheading, matrixSummary, sourceVerified, secondarySourceLabel } from "../types";
import { tx } from "../utils/translations";
interface AlliedMatrixProps { standard: StandardResult; language?: Language; }
const groupIcons: Record<string, typeof Wrench> = { "Conductor Specs": Layers3, "Armouring Material": Wrench, "Compulsory Test Methods": FlaskConical, "Physical tests": FlaskConical, "Chemical analysis": ShieldCheck, "Safety Codes": ShieldCheck, "Regulatory Orders": ShieldCheck };
const groupHi: Record<string, string> = { "Conductor Specs": "कंडक्टर विनिर्देश", "Armouring Material": "आर्मरिंग सामग्री", "Compulsory Test Methods": "अनिवार्य परीक्षण विधियाँ", "Physical tests": "भौतिक परीक्षण", "Chemical analysis": "रासायनिक विश्लेषण", "Safety Codes": "सुरक्षा संहिताएँ", "Regulatory Orders": "नियामक आदेश" };
const relevanceHi: Record<string, string> = { "Conductor material, resistance and stranding": "कंडक्टर सामग्री, प्रतिरोध और स्ट्रैंडिंग", "Insulation and sheath compound requirements": "इंसुलेशन और शीथ यौगिक आवश्यकताएँ", "Armour material and mechanical properties": "आर्मर सामग्री और यांत्रिक गुण", "Vertical flame propagation / fire performance": "ऊर्ध्वाधर ज्वाला प्रसार और अग्नि प्रदर्शन", "Routine electrical acceptance test": "नियमित विद्युत स्वीकृति परीक्षण", "Low-smoke performance evidence": "कम-धुआँ प्रदर्शन प्रमाण", "Fineness, soundness, setting time and strength": "सूक्ष्मता, स्थायित्व, सेटिंग समय और शक्ति", "Chemical composition and loss on ignition": "रासायनिक संरचना और इग्निशन पर हानि", "Yield strength, elongation and tensile test procedure": "उपज शक्ति, बढ़ाव और तन्यता परीक्षण विधि", "Bar dimensions, mass and tolerance reference": "बार आयाम, द्रव्यमान और सहनशीलता संदर्भ", "Seismic design compatibility": "भूकंपीय डिजाइन अनुकूलता", "Electrical safety and abnormal operation": "विद्युत सुरक्षा और असामान्य संचालन", "Insulation, leakage and dielectric tests": "इंसुलेशन, लीकेज और डाइलेक्ट्रिक परीक्षण", "Registration and marking requirements": "पंजीकरण और चिह्नांकन आवश्यकताएँ" };
export default function AlliedMatrix({ standard, language = "en" }: AlliedMatrixProps) { const [open, setOpen] = useState<Record<string, boolean>>({ [allGroups(standard)[0]]: true }); const hi = language === "hi"; return <article className="matrix-card card-surface"><div className="card-topline"><span className="eyebrow amber-eyebrow">{secondarySourceLabel()}</span><span className="record-id">{matrixSummary(standard)}</span></div><div className="panel-heading"><div><h2>{hi ? tx(language, "allied") : matrixHeading()}</h2><p>{hi ? "प्राथमिक मानक से जुड़े और सत्यापित संदर्भ" : matrixSubheading()}</p></div><span className="verified-count"><ShieldCheck size={14} /> {hi ? "सभी सत्यापित" : "all verified"}</span></div><div className="matrix-list">{allGroups(standard).map((group) => { const Icon = groupIcons[group]; const items = standard.allied.filter((item) => item.group === group); const isOpen = open[group]; return <div className={`matrix-group ${isOpen ? "expanded" : ""}`} key={group}><button className="matrix-group-button" onClick={() => setOpen({ ...open, [group]: !isOpen })}><span className="group-icon"><Icon size={15} /></span><span className="group-title"><strong>{hi ? groupHi[group] ?? group : group}</strong><small>{hi ? "मानक आवश्यकताएँ और प्रमाण" : groupDescription(group)}</small></span><span className="group-count mono">{items.length.toString().padStart(2, "0")}</span>{isOpen ? <ChevronDown size={16} /> : <ChevronRight size={16} />}</button>{isOpen && <div className="matrix-items">{items.map((item: AlliedStandard) => <div className="matrix-item" key={item.code}><div><div className="matrix-code mono">{item.code}</div><div className="matrix-name">{item.title}</div><div className="matrix-relevance">{hi ? relevanceHi[item.relevance] ?? item.relevance : item.relevance}</div></div><div className="matrix-item-right"><span className="group-code mono">{matrixGroupCode(group)}</span>{sourceVerified(item) && <ShieldCheck size={14} className="verified-icon" />}</div></div>)}</div>}</div>; })}</div><div className="matrix-footer"><span>{hi ? "संदर्भ प्राथमिक मानक के खंडों से जुड़े हैं" : "References are linked to primary standard clauses"}</span><span className="mono">{standard.allied.length} refs</span></div></article>; }
