import { ArrowRight, ChevronRight, CircleDot, FileCheck2, Gavel, GitBranch, Info, Link2, ShieldCheck, TestTube2, X } from "lucide-react";
import type { GraphNode } from "../types";
import { graphColor, graphEdges, graphKindMeta, graphNodes, graphNodeCode, graphNodeCountCopy, graphRelationCountCopy, graphSubheading, graphTypeName, selectedGraphDetail, graphNodeIcon, graphInspectorPrompt, graphInspectorTitle, graphAccessibleText } from "../types";

interface KnowledgeGraphProps { selectedNode: string; setSelectedNode: (id: string) => void; }

export default function KnowledgeGraph({ selectedNode, setSelectedNode }: KnowledgeGraphProps) {
  const selected = graphNodes.find((node) => node.id === selectedNode) ?? graphNodes[0];
  const nodePoint = (node: GraphNode) => ({ x: node.x * 7.2 + 20, y: node.y * 4.65 + 18 });
  return <section className="graph-view">
    <div className="view-heading-row"><div><div className="section-kicker"><span className="kicker-dot purple-dot" /> GRAPH / CITATION LOCKED</div><h1>Normative knowledge graph</h1><p>{graphSubheading()}</p></div><div className="graph-heading-stats"><span><strong>{graphNodes.length}</strong> nodes</span><span><strong>{graphEdges.length}</strong> directed edges</span><span><ShieldCheck size={14} /> verified</span></div></div>
    <div className="graph-layout"><div className="graph-canvas card-surface" aria-label={graphAccessibleText()}><div className="graph-canvas-header"><span className="eyebrow blue-eyebrow">LIVE RELATIONSHIP CANVAS</span><span className="mono">IS 7098 / NETWORK VIEW</span></div><svg className="graph-svg" viewBox="0 0 740 480" role="img"><defs><filter id="glow"><feGaussianBlur stdDeviation="4" result="coloredBlur" /><feMerge><feMergeNode in="coloredBlur" /><feMergeNode in="SourceGraphic" /></feMerge></filter><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#475569" /></marker></defs>{graphEdges.map((edge) => { const from = nodePoint(graphNodes.find((node) => node.id === edge.from)!); const to = nodePoint(graphNodes.find((node) => node.id === edge.to)!); const isActive = edge.from === selectedNode || edge.to === selectedNode; return <g key={`${edge.from}-${edge.to}`} className={isActive ? "edge-group active" : "edge-group"}><line x1={from.x} y1={from.y} x2={to.x} y2={to.y} markerEnd="url(#arrow)" /><text x={(from.x + to.x) / 2} y={(from.y + to.y) / 2 - 8}>{edge.label}</text></g>; })}{graphNodes.map((node) => { const point = nodePoint(node); const color = graphColor(node.kind); const active = node.id === selectedNode; return <g key={node.id} className={`graph-node ${active ? "selected" : ""}`} transform={`translate(${point.x},${point.y})`} onClick={() => setSelectedNode(node.id)} role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") setSelectedNode(node.id); }}><circle r={node.kind === "primary" ? 40 : 30} fill="#101827" stroke={color} strokeWidth={active ? 3 : 2} filter={active ? "url(#glow)" : undefined} /><circle r={node.kind === "primary" ? 31 : 22} fill={`${color}22`} stroke={`${color}77`} /><text className="node-icon" y="4" fill={color}>{graphNodeIcon(node.kind)}</text>{graphNodeCode(node).split(" ").map((line, index) => <text key={line} className="node-label" y={node.kind === "primary" ? 59 + index * 14 : 48 + index * 14}>{line}</text>)}<circle className="node-pulse" r="4" cx={node.kind === "primary" ? 29 : 22} cy={node.kind === "primary" ? -29 : -22} fill={color} /></g>; })}</svg><div className="graph-legend">{Object.entries(graphKindMeta).map(([key, value]) => <span key={key}><i style={{ background: value.color }} />{value.label}</span>)}</div></div>
      <aside className="graph-inspector card-surface"><div className="inspector-header"><div><span className="eyebrow purple-eyebrow">NODE INSPECTOR</span><h2>{graphInspectorTitle(selected)}</h2></div><button className="icon-button" onClick={() => setSelectedNode("primary")} aria-label="Reset graph selection"><X size={15} /></button></div><div className="inspector-type" style={{ color: graphColor(selected.kind), borderColor: `${graphColor(selected.kind)}55`, background: `${graphColor(selected.kind)}12` }}><CircleDot size={13} /> {graphTypeName(selected)}</div><div className="inspector-main"><div className="inspector-code mono">{graphNodeCode(selected)}</div><p>{selectedGraphDetail(selected)}</p></div><div className="inspector-relations"><div className="block-label"><Link2 size={14} /> DIRECT RELATIONSHIPS</div>{graphEdges.filter((edge) => edge.from === selected.id || edge.to === selected.id).map((edge) => { const other = edge.from === selected.id ? edge.to : edge.from; const otherNode = graphNodes.find((node) => node.id === other)!; return <button className="relation-row" key={`${edge.from}-${edge.to}`} onClick={() => setSelectedNode(other)}><span className="relation-icon" style={{ color: graphColor(otherNode.kind) }}>{otherNode.kind === "qco_mandates" ? <Gavel size={14} /> : otherNode.kind === "test_methods" ? <TestTube2 size={14} /> : <GitBranch size={14} />}</span><span><strong>{edge.label}</strong><small>{graphNodeCode(otherNode)}</small></span><ArrowRight size={14} /></button>; })}</div><div className="inspector-clause"><div className="block-label"><FileCheck2 size={14} /> OFFICIAL CLAUSE CONTEXT</div><p>{selected.kind === "primary" ? "The central standard governs product construction and acceptance. Follow each linked reference for the complete procurement evidence chain." : selected.detail}</p></div><div className="inspector-footer"><Info size={13} /> {graphInspectorPrompt()}</div></aside></div>
  </section>;
}
