import { ArrowRight, CircleDot, FileCheck2, Gavel, GitBranch, Info, Link2, ShieldCheck, TestTube2, X } from "lucide-react";
import type { GraphNode, Language } from "../types";
import { graphColor, graphKindMeta, graphNodeCode, graphTypeName, selectedGraphDetail, graphNodeIcon, graphInspectorPrompt, graphInspectorTitle, graphAccessibleText } from "../types";
import type { DomainKey } from "../mockData";
import { domainLabels, domainShortLabels, graphByDomain } from "../mockData";
import { graphKindLabel, localizeGraphNode, localizedRelation, tx } from "../utils/translations";

interface KnowledgeGraphProps { selectedNode: string; setSelectedNode: (id: string) => void; domain: DomainKey; setDomain: (domain: DomainKey) => void; language?: Language; }

export default function KnowledgeGraph({ selectedNode, setSelectedNode, domain, setDomain, language = "en" }: KnowledgeGraphProps) {
  const graph = graphByDomain[domain];
  const localizedNodes = graph.nodes.map((node) => localizeGraphNode(node, language));
  const localizedEdges = graph.edges.map((edge) => ({ ...edge, label: localizedRelation(edge.label, language) }));
  const selected = localizedNodes.find((node) => node.id === selectedNode) ?? localizedNodes[0];
  const nodePoint = (node: GraphNode) => ({ x: node.x * 7.2 + 20, y: node.y * 4.65 + 18 });
  return <section className="graph-view">
    <div className="view-heading-row"><div><div className="section-kicker"><span className="kicker-dot purple-dot" /> GRAPH / CITATION LOCKED</div><h1>{language === "hi" ? "मानक ज्ञान ग्राफ" : "Normative knowledge graph"}</h1><p>{language === "hi" ? "चार खरीद क्षेत्रों में प्रत्येक मानक, परीक्षण विधि, सामग्री इनपुट और गुणवत्ता आदेश का पता लगाएँ।" : "Trace every standard, test method, material input and legal order across four procurement domains."}</p></div><div className="graph-heading-stats"><span><strong>{graph.nodes.length}</strong> nodes</span><span><strong>{graph.edges.length}</strong> directed edges</span><span><ShieldCheck size={14} /> verified</span></div></div>
    <div className="domain-selector"><div className="domain-selector-label"><GitBranch size={14} /> {language === "hi" ? "क्षेत्र चुनें" : "SELECT DOMAIN"}</div>{(Object.keys(domainLabels) as DomainKey[]).map((key) => <button className={domain === key ? "active" : ""} key={key} onClick={() => { setDomain(key); setSelectedNode("primary"); }}><span className="mono">0{(Object.keys(domainLabels) as DomainKey[]).indexOf(key) + 1}</span>{domainLabels[key]}<small>{domainShortLabels[key]}</small></button>)}</div>
    <div className="graph-layout"><div className="graph-canvas card-surface" aria-label={graphAccessibleText()}><div className="graph-canvas-header"><span className="eyebrow blue-eyebrow">{language === "hi" ? "सक्रिय संबंध कैनवास" : "LIVE RELATIONSHIP CANVAS"}</span><span className="mono">{domainShortLabels[domain]} / {language === "hi" ? "नेटवर्क दृश्य" : "NETWORK VIEW"}</span></div><svg className="graph-svg" viewBox="0 0 740 480" role="img"><defs><filter id="glow"><feGaussianBlur stdDeviation="4" result="coloredBlur" /><feMerge><feMergeNode in="coloredBlur" /><feMergeNode in="SourceGraphic" /></feMerge></filter><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L7,3 z" fill="#475569" /></marker></defs>{localizedEdges.map((edge) => { const from = nodePoint(localizedNodes.find((node) => node.id === edge.from)!); const to = nodePoint(localizedNodes.find((node) => node.id === edge.to)!); const isActive = edge.from === selectedNode || edge.to === selectedNode; return <g key={`${edge.from}-${edge.to}`} className={isActive ? "edge-group active" : "edge-group"}><line x1={from.x} y1={from.y} x2={to.x} y2={to.y} markerEnd="url(#arrow)" /><text x={(from.x + to.x) / 2} y={(from.y + to.y) / 2 - 8}>{edge.label}</text></g>; })}{localizedNodes.map((node) => { const point = nodePoint(node); const color = graphColor(node.kind); const active = node.id === selected.id; return <g key={node.id} className={`graph-node ${active ? "selected" : ""}`} transform={`translate(${point.x},${point.y})`} onClick={() => setSelectedNode(node.id)} role="button" tabIndex={0} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") setSelectedNode(node.id); }}><circle r={node.kind === "primary" ? 40 : 30} fill="#101827" stroke={color} strokeWidth={active ? 3 : 2} filter={active ? "url(#glow)" : undefined} /><circle r={node.kind === "primary" ? 31 : 22} fill={`${color}22`} stroke={`${color}77`} /><text className="node-icon" y="4" fill={color}>{graphNodeIcon(node.kind)}</text>{graphNodeCode(node).split(" ").map((line) => <text key={line} className="node-label" y={node.kind === "primary" ? 59 : 48}>{line}</text>)}<circle className="node-pulse" r="4" cx={node.kind === "primary" ? 29 : 22} cy={node.kind === "primary" ? -29 : -22} fill={color} /></g>; })}</svg><div className="graph-legend">{Object.entries(graphKindMeta).map(([key, value]) => <span key={key}><i style={{ background: value.color }} />{graphKindLabel(key as GraphNode["kind"], language)}</span>)}</div></div>
      <aside className="graph-inspector card-surface"><div className="inspector-header"><div><span className="eyebrow purple-eyebrow">{tx(language, "graphInspector")}</span><h2>{graphInspectorTitle(selected)}</h2></div><button className="icon-button" onClick={() => setSelectedNode("primary")} aria-label="Reset graph selection"><X size={15} /></button></div><div className="inspector-type" style={{ color: graphColor(selected.kind), borderColor: `${graphColor(selected.kind)}55`, background: `${graphColor(selected.kind)}12` }}><CircleDot size={13} /> {graphKindLabel(selected.kind, language)}</div><div className="inspector-main"><div className="inspector-code mono">{graphNodeCode(selected)}</div><p>{selected.detail}</p></div><div className="inspector-relations"><div className="block-label"><Link2 size={14} /> {tx(language, "directRelationships")}</div>{localizedEdges.filter((edge) => edge.from === selected.id || edge.to === selected.id).map((edge) => { const other = edge.from === selected.id ? edge.to : edge.from; const otherNode = localizedNodes.find((node) => node.id === other)!; return <button className="relation-row" key={`${edge.from}-${edge.to}`} onClick={() => setSelectedNode(other)}><span className="relation-icon" style={{ color: graphColor(otherNode.kind) }}>{otherNode.kind === "qco_mandates" ? <Gavel size={14} /> : otherNode.kind === "test_methods" ? <TestTube2 size={14} /> : <GitBranch size={14} />}</span><span><strong>{edge.label}</strong><small>{graphNodeCode(otherNode)}</small></span><ArrowRight size={14} /></button>; })}</div><div className="inspector-clause"><div className="block-label"><FileCheck2 size={14} /> {tx(language, "exactClause")}</div><p>{selected.detail}</p></div><div className="inspector-footer"><Info size={13} /> {graphInspectorPrompt()}</div></aside></div>
  </section>;
}
