import { ArrowUpRight, BadgeCheck, BriefcaseBusiness, CalendarClock, CheckCircle2, ChevronRight, FileEdit, History, LockKeyhole, X } from "lucide-react";
import { auditHistory, savedDrafts } from "../mockData";
import type { Language } from "../types";
import { tx } from "../utils/translations";

interface OfficerProfileDrawerProps { open: boolean; onClose: () => void; language: Language; onLoadDraft: (standard: string) => void; }
export default function OfficerProfileDrawer({ open, onClose, language, onLoadDraft }: OfficerProfileDrawerProps) {
  return <><div className={`drawer-backdrop ${open ? "open" : ""}`} onClick={onClose} /><aside className={`officer-drawer ${open ? "open" : ""}`} aria-hidden={!open} aria-label={tx(language, "openProfile")}><div className="drawer-header"><div><span className="drawer-kicker"><BadgeCheck size={13} /> NIC CREDENTIALLED SESSION</span><h2>{tx(language, "officer")}</h2><p>{tx(language, "officerRole")} · {tx(language, "department")}</p></div><button className="icon-button" onClick={onClose} aria-label={tx(language, "close")}><X size={17} /></button></div><div className="credential-card"><div className="credential-icon"><LockKeyhole size={18} /></div><div><strong>{tx(language, "activeCredential")}</strong><span>Issued by National Informatics Centre · Last verified 22 Sep 2026</span></div><CheckCircle2 size={16} /></div><section className="drawer-section"><div className="drawer-section-heading"><div><span className="drawer-eyebrow"><FileEdit size={13} /> {tx(language, "savedDrafts")}</span><h3>Working specifications</h3></div><span className="drawer-count">{savedDrafts.length.toString().padStart(2, "0")}</span></div>{savedDrafts.map((draft) => <div className="drawer-draft" key={draft.id}><div className="drawer-draft-icon"><FileEdit size={14} /></div><div className="drawer-draft-copy"><strong>{draft.title}</strong><small className="mono">{draft.id} · {draft.standard}</small><span><CalendarClock size={11} /> {draft.updated}</span></div><button className="drawer-load" onClick={() => { onLoadDraft(draft.standard); onClose(); }}>{tx(language, "loadSynthesizer")} <ChevronRight size={13} /></button></div>)}</section><section className="drawer-section"><div className="drawer-section-heading"><div><span className="drawer-eyebrow bronze"><History size={13} /> {tx(language, "auditHistory")}</span><h3>Previous tender scans</h3></div><span className="drawer-count">{auditHistory.length.toString().padStart(2, "0")}</span></div><div className="drawer-history-table">{auditHistory.map((entry) => <div className="drawer-history-row" key={entry.id}><div><strong>{entry.file}</strong><small className="mono">{entry.id} · {entry.date}</small></div><span className={`drawer-history-status ${entry.status === "Fully Compliant" ? "good" : entry.status === "Audit Pending" ? "pending" : "resolved"}`}>{entry.status}</span></div>)}</div></section><div className="drawer-footer"><BriefcaseBusiness size={14} /><span>Official workspace records are private to this officer session.</span><ArrowUpRight size={13} /></div></aside></>;
}
