import { Archive, ArrowUpRight, BookOpen, CheckCircle2, Clock3, FileEdit, FolderOpen, History, LockKeyhole, MoreHorizontal, Plus, Search, ShieldCheck } from "lucide-react";
import { auditHistory, savedDrafts } from "../mockData";

interface OfficerWorkspaceProps { onLoadDraft: (standard: string) => void; }

export default function OfficerWorkspace({ onLoadDraft }: OfficerWorkspaceProps) {
  return <section className="workspace-view">
    <div className="view-heading-row"><div><div className="section-kicker"><span className="kicker-dot green-dot" /> OFFICER WORKSPACE / AUTHENTICATED SESSION</div><h1>My procurement workspace</h1><p>Save working clauses, revisit audit findings and keep every tender decision source-backed.</p></div><div className="workspace-profile"><div className="profile-avatar">SS</div><div><strong>S. Sharma</strong><span>Exec. Engineer · PWD / GeM Officer</span><small className="mono">ID #GOV-8941</small></div><LockKeyhole size={14} /></div></div>
    <div className="workspace-metrics"><div><span className="workspace-metric-icon"><FileEdit size={15} /></span><strong>03</strong><span>Saved drafts</span></div><div><span className="workspace-metric-icon"><History size={15} /></span><strong>12</strong><span>Audit records</span></div><div><span className="workspace-metric-icon"><ShieldCheck size={15} /></span><strong>96%</strong><span>Compliant issue rate</span></div><div><span className="workspace-metric-icon"><Clock3 size={15} /></span><strong>04:12</strong><span>Next catalogue sync</span></div></div>
    <div className="workspace-grid"><article className="workspace-card card-surface"><div className="workspace-card-heading"><div><span className="eyebrow blue-eyebrow"><FolderOpen size={13} /> SAVED TENDER DRAFTS</span><h2>Continue a working specification</h2></div><button className="secondary-button"><Plus size={14} /> New draft</button></div><div className="draft-table"><div className="draft-table-head"><span>DOCUMENT / STANDARD</span><span>LAST UPDATED</span><span>STATE</span><span /></div>{savedDrafts.map((draft) => <button className="draft-row" key={draft.id} onClick={() => onLoadDraft(draft.standard)}><span className="draft-name"><span className="draft-icon"><FileEdit size={14} /></span><span><strong>{draft.title}</strong><small className="mono">{draft.id} · {draft.standard}</small></span></span><span className="draft-date mono">{draft.updated}</span><span className={`draft-status ${draft.status === "Saved" ? "saved" : "review"}`}>{draft.status === "Saved" ? <CheckCircle2 size={13} /> : <Clock3 size={13} />}{draft.status}</span><ArrowUpRight size={14} className="row-arrow" /></button>)}</div></article>
      <article className="workspace-card card-surface"><div className="workspace-card-heading"><div><span className="eyebrow amber-eyebrow"><History size={13} /> AUDIT HISTORY</span><h2>Recent tender checks</h2></div><button className="icon-button"><MoreHorizontal size={16} /></button></div><div className="history-list">{auditHistory.map((entry) => <div className="history-row" key={entry.id}><div className="history-icon"><Archive size={14} /></div><div className="history-copy"><strong>{entry.file}</strong><small className="mono">{entry.id} · {entry.date}</small></div><span className={`history-status ${entry.status === "Fully Compliant" ? "good" : entry.status === "Audit Pending" ? "pending" : "resolved"}`}>{entry.status}</span></div>)}</div><div className="workspace-card-footer"><span><ShieldCheck size={13} /> All records are private to this officer session.</span><button className="text-button">Open full history <ArrowUpRight size={13} /></button></div></article></div>
    <div className="workspace-bottom-note"><BookOpen size={15} /><span><strong>Source-lock policy:</strong> saved drafts preserve the exact BIS references, amendment set and QCO basis used during synthesis.</span><Search size={14} /><span className="mono">LAST LOGIN · 22 SEP 2026 / 08:42 IST</span></div>
  </section>;
}
