import { ArrowUpRight, BadgeCheck, BriefcaseBusiness, CalendarClock, CheckCircle2, ChevronRight, FileEdit, History, LockKeyhole, X } from "lucide-react";
import { auditHistory, savedDrafts } from "../mockData";
import type { Language } from "../types";
import { tx } from "../utils/translations";
interface OfficerProfileDrawerProps { open: boolean; onClose: () => void; language: Language; onLoadDraft: (standard: string) => void; }
export default function OfficerProfileDrawer({ open, onClose, language, onLoadDraft }: OfficerProfileDrawerProps) {
  if (!open) return null;
  return <><button className="profile-popover-backdrop" aria-label={tx(language, "close")} onClick={onClose} /><aside className="officer-popover" role="dialog" aria-modal="true" aria-label={tx(language, "openProfile")}><div className="popover-header"><div><span className="drawer-kicker"><BadgeCheck size={12} /> NIC CREDENTIALLED SESSION</span><h2>{tx(language, "officer")}</h2><p>{tx(language, "officerRole")} · {tx(language, "department")}</p></div><button className="icon-button" onClick={onClose} aria-label={tx(language, "close")}><X size={15} /></button></div><div className="credential-card"><div className="credential-icon"><LockKeyhole size={16} /></div><div><strong>{tx(language, "activeCredential")}</strong><span>Issued by National Informatics Centre · Last verified 22 Sep 2026</span></div><CheckCircle2 size={14} /></div><section className="popover-section"><div className="popover-section-heading"><div><span className="drawer-eyebrow"><FileEdit size={12} /> {tx(language, "savedDrafts")}</span><h3>{language === "hi" ? "कार्यशील विनिर्देश" : "Working specifications"}</h3></div><span className="drawer-count">{savedDrafts.length.toString().padStart(2, "0")}</span></div>{savedDrafts.slice(0, 3).map((draft) => <div className="popover-draft" key={draft.id}><div className="drawer-draft-icon"><FileEdit size={13} /></div><div className="drawer-draft-copy"><strong>{draft.title}</strong><small className="mono">{draft.id} · {draft.standard}</small><span><CalendarClock size={10} /> {draft.updated}</span></div><button className="drawer-load" onClick={() => { onLoadDraft(draft.standard); onClose(); }}>{language === "hi" ? "खोलें" : "Open"} <ChevronRight size={12} /></button></div>)}</section><section className="popover-section"><div className="popover-section-heading"><div><span className="drawer-eyebrow bronze"><History size={12} /> {tx(language, "auditHistory")}</span><h3>{language === "hi" ? "पिछली निविदा जाँच" : "Previous tender scans"}</h3></div><span className="drawer-count">{auditHistory.length.toString().padStart(2, "0")}</span></div><div className="popover-history">{auditHistory.slice(0, 3).map((entry) => <div className="popover-history-row" key={entry.id}><div><strong>{entry.file}</strong><small className="mono">{entry.id} · {entry.date}</small></div><span className={`drawer-history-status ${entry.status === "Fully Compliant" ? "good" : entry.status === "Audit Pending" ? "pending" : "resolved"}`}>{entry.status}</span></div>)}</div></section><div className="popover-footer"><BriefcaseBusiness size={13} /><span>{language === "hi" ? "यह सत्र निजी है।" : "Private officer session."}</span><ArrowUpRight size={12} /></div></aside></>;
}
